name: Build pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "requirements.txt"
      - "mkdocs.yml"

  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "requirements.txt"
      - "mkdocs.yml"

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.KUBE_MEDIA_APP_ID }}
          private_key: ${{ secrets.KUBE_MEDIA_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build website
        run: mkdocs build --strict

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/kube-media/kube-media.git /tmp/kube-media
          cd /tmp/kube-media
          git config user.name "kube-media[bot]"
          git config user.email "kube-media[bot]@users.noreply.github.com"
          git fetch --all
          git checkout -b gh-pages origin/gh-pages
          cp -r $GITHUB_WORKSPACE/site/* /tmp/kube-media/

          git add .
          git commit -m "chore: Auto-update website [skip ci]"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}